# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_auto_20170202_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salonstore',
            old_name='id',
            new_name='salon_id',
        ),
    ]
