# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_auto_20170202_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_cover_photo',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='F:\\SalonDjango\\ravishing_salon\\media/photo/'),
        ),
    ]
