# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_auto_20170202_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_cover_photo',
            field=models.BooleanField(default=0),
        ),
    ]
