# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_auto_20170202_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salonstore',
            old_name='salon_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
