# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_auto_20170202_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonstore',
            name='address_2',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
