# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_auto_20170202_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='salonstore',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
