# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import salon.models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0012_auto_20170203_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.TextField(default=salon.models.user_directory_path),
        ),
    ]
